/**
 * 三选卡池文案与可叠 id（对齐 design / UPGRADE_POOL）。
 * UpgradeId 联合类型仍在 domain；此处 id 须与之同步。
 */

export type UpgradePoolKind = 'stat' | 'special'

export type UpgradePoolRow = {
  id: string
  name: string
  desc: string
  kind: UpgradePoolKind
}

export const UPGRADE_POOL_ROWS: UpgradePoolRow[] = [
  { id: 'damage', name: '强击', desc: '全伤害提升', kind: 'stat' },
  { id: 'haste', name: '迅捷', desc: '武/魔冷却加快', kind: 'stat' },
  { id: 'fire_rate', name: '火球 · 冷却', desc: '火球冷却缩短', kind: 'stat' },
  { id: 'max_hp', name: '生命', desc: '生命上限提升并回满', kind: 'stat' },
  { id: 'hp_regen', name: '回春', desc: '持续回血', kind: 'stat' },
  { id: 'move_speed', name: '滑步', desc: '移速提升', kind: 'stat' },
  { id: 'heat_decay', name: '保温', desc: '热度回落减慢', kind: 'stat' },
  { id: 'luck', name: '幸运', desc: '更高概率抽到高档属性', kind: 'stat' },
  { id: 'armor', name: '护甲', desc: '挨打少掉血（减伤%，有顶）', kind: 'stat' },
  { id: 'dodge', name: '闪避几率', desc: '受击时有概率不挨打（有顶）', kind: 'stat' },
  { id: 'crit', name: '暴击', desc: '暴击率提升（幸运不管暴击）', kind: 'stat' },
  { id: 'growth', name: '成长', desc: '经验获取提升', kind: 'stat' },
  { id: 'magnet', name: '磁铁', desc: '金币吸得更远', kind: 'stat' },
  { id: 'cast_reach', name: '施法距离', desc: '各门第一下打得更远', kind: 'stat' },
  { id: 'cast_area', name: '施法范围', desc: '各门这一下铺更大、控更久（无顶，怪多更赚）', kind: 'stat' },
  { id: 'star_rain', name: '落岩 · 勤', desc: '落岩砸得更勤', kind: 'stat' },
  { id: 'chain_reach', name: '雷链 · 范围', desc: '雷链首跳距与跳距变长', kind: 'stat' },
  { id: 'melee_power', name: '专精 · 击退', desc: '风息推得更远', kind: 'special' },
  { id: 'orb_split', name: '专精 · 分裂', desc: '火球打中后再找一人打一下', kind: 'special' },
  { id: 'aura_slow', name: '专精 · 缓速', desc: '霜环减速更狠', kind: 'special' },
  { id: 'chain_fork', name: '专精 · 弹射次数', desc: '雷链多跳 1 次', kind: 'special' },
  { id: 'star_volley', name: '专精 · 多发', desc: '主手 CD 转好多出一手', kind: 'special' },
  { id: 'star_crater', name: '落岩 · 坑', desc: '落岩坑更大更久', kind: 'special' },
  { id: 'elem_break', name: '破甲', desc: '学一次 · 打中叠满削他护甲', kind: 'special' },
  { id: 'elem_explode', name: '爆炸', desc: '学一次 · 打中叠满在他身上炸一圈', kind: 'special' },
  { id: 'elem_freeze', name: '冻结', desc: '学一次 · 打中叠满定身', kind: 'special' },
  { id: 'elem_amp', name: '增伤', desc: '学一次 · 打中叠满后他更好打', kind: 'special' },
  { id: 'elem_weak', name: '虚弱', desc: '学一次 · 打中叠满后他打得更弱', kind: 'special' },
  { id: 'heat_cap', name: '热度上限', desc: '热度上限 +25', kind: 'special' },
  { id: 'beat_bonus', name: '拍点加码', desc: '踩拍时初始武器额外加码', kind: 'special' },
  { id: 'learn_flame', name: '习得 · 风息', desc: '解锁风息短锥（拍点仍只强化初始武器）', kind: 'special' },
  { id: 'learn_orb', name: '习得 · 火球', desc: '解锁火球自动发球（拍点仍只强化初始武器）', kind: 'special' },
  { id: 'learn_aura', name: '习得 · 霜环', desc: '解锁霜环（拍点仍只强化初始武器）', kind: 'special' },
  { id: 'learn_chain', name: '习得 · 雷链', desc: '解锁雷链弹跳（拍点仍只强化初始武器）', kind: 'special' },
  { id: 'learn_star', name: '习得 · 落岩', desc: '解锁落岩砸点（拍点仍只强化初始武器）', kind: 'special' },
  { id: 'flame_dmg', name: '风息 · 伤', desc: '风息伤害提升', kind: 'stat' },
  { id: 'flame_cd', name: '风息 · 冷却', desc: '风息冷却缩短', kind: 'stat' },
  { id: 'melee_range', name: '风息 · 范围', desc: '风息锥更长更宽', kind: 'stat' },
  { id: 'orb_dmg', name: '火球 · 伤', desc: '火球伤害提升', kind: 'stat' },
  { id: 'aura_dmg', name: '霜环 · 伤', desc: '霜环伤害提升', kind: 'stat' },
  { id: 'aura_cd', name: '霜环 · 冷却', desc: '霜环跳伤间隔缩短', kind: 'stat' },
  { id: 'aura_widen', name: '霜环 · 范围', desc: '霜环半径变大', kind: 'stat' },
  { id: 'chain_dmg', name: '雷链 · 伤', desc: '雷链伤害提升', kind: 'stat' },
  { id: 'chain_cd', name: '雷链 · 冷却', desc: '雷链冷却缩短', kind: 'stat' },
  { id: 'star_dmg', name: '落岩 · 伤', desc: '落岩伤害提升', kind: 'stat' },
  { id: 'star_scale', name: '落岩 · 范围', desc: '落岩落点变大', kind: 'stat' },
  { id: 'fuse_flame', name: '融合 · 风息', desc: '关末融进主手 · 打中附带击退', kind: 'special' },
  { id: 'fuse_orb', name: '融合 · 火球', desc: '关末融进主手 · 打中后分裂', kind: 'special' },
  { id: 'fuse_aura', name: '融合 · 霜环', desc: '关末融进主手 · 打中附带减速', kind: 'special' },
  { id: 'fuse_chain', name: '融合 · 雷链', desc: '关末融进主手 · 打中后再串一人', kind: 'special' },
  { id: 'fuse_star', name: '融合 · 落岩', desc: '关末融进主手 · CD 转好多出一手', kind: 'special' },
  { id: 'relic_ward', name: '护盾', desc: '挡一层，碎了后过几秒或击杀刷新', kind: 'special' },
  { id: 'relic_leech', name: '吸血', desc: '打人回血（有顶、有衰减）', kind: 'special' },
  { id: 'relic_carapace', name: '护甲成长', desc: '每过一波叠一层减伤（有顶）', kind: 'special' },
  { id: 'relic_greed', name: '拾荒', desc: '本局金币获取 +40%', kind: 'special' },
  { id: 'relic_ember', name: '余烬', desc: '位移闪避更省热度', kind: 'special' },
  { id: 'relic_spark', name: '起势', desc: '每波开场 Fever 有一段保底', kind: 'special' },
  { id: 'rhythm_window', name: '宽判', desc: '判定窗略放宽', kind: 'special' },
  { id: 'rhythm_fever_gain', name: '热槽', desc: 'Fever 涨得更快（和热血相乘）', kind: 'special' },
  { id: 'rhythm_fever_hold', name: '延烧', desc: 'Fever 窗口更长', kind: 'special' },
  { id: 'rhythm_combo_soft', name: '韧击', desc: 'Miss 少砍一半连击', kind: 'special' },
  { id: 'rhythm_combo_cap', name: '连击顶', desc: '连击伤顶上移', kind: 'special' },
]

/** 可叠的升级 id（与上表 id 对齐）。 */
export const STACKABLE_IDS = [
  'damage',
  'haste',
  'fire_rate',
  'beat_bonus',
  'melee_power',
  'max_hp',
  'hp_regen',
  'aura_slow',
  'orb_split',
  'chain_fork',
  'chain_reach',
  'luck',
  'armor',
  'dodge',
  'crit',
  'growth',
  'magnet',
  'cast_reach',
  'cast_area',
  'star_rain',
  'star_volley',
  'flame_dmg',
  'flame_cd',
  'melee_range',
  'orb_dmg',
  'aura_dmg',
  'aura_cd',
  'aura_widen',
  'chain_dmg',
  'chain_cd',
  'star_dmg',
  'star_scale',
] as const

/** 属性卡三档展示文案（缺则回退到 pool.desc）。 */
export const GRADE_DETAILS: Record<string, readonly [string, string, string]> = {
  damage: ['全伤害 +10%', '全伤害 +18%', '全伤害 +28%'],
  haste: ['冷却 -3%', '冷却 -7%', '冷却 -12%'],
  fire_rate: ['火球 CD -6%', '火球 CD -12%', '火球 CD -20%'],
  flame_dmg: ['风息伤 +10%', '风息伤 +16%', '风息伤 +24%'],
  flame_cd: ['风息 CD -3%', '风息 CD -6%', '风息 CD -10%'],
  melee_range: ['锥面积 +6%', '锥面积 +12%', '锥面积 +18%'],
  orb_dmg: ['火球伤 +10%', '火球伤 +16%', '火球伤 +24%'],
  aura_dmg: ['霜环伤 +10%', '霜环伤 +16%', '霜环伤 +24%'],
  aura_cd: ['霜环间隔 -3%', '霜环间隔 -6%', '霜环间隔 -10%'],
  aura_widen: ['霜环面积 +6%', '霜环面积 +12%', '霜环面积 +20%'],
  chain_dmg: ['雷链伤 +10%', '雷链伤 +16%', '雷链伤 +24%'],
  chain_cd: ['雷链 CD -3%', '雷链 CD -6%', '雷链 CD -10%'],
  star_dmg: ['落岩伤 +10%', '落岩伤 +16%', '落岩伤 +24%'],
  star_scale: ['落点面积 +6%', '落点面积 +10%', '落点面积 +14%'],
  max_hp: ['上限 +1 并回满', '上限 +1 并回满', '上限 +2 并回满'],
  hp_regen: ['回血 +0.12/秒', '回血 +0.20/秒', '回血 +0.32/秒'],
  move_speed: ['移速 +6%', '移速 +12%', '移速 +20%'],
  heat_decay: ['回落 -12%', '回落 -22%', '回落 -35%'],
  luck: ['幸运 +1', '幸运 +2', '幸运 +3'],
  armor: ['减伤 +5%', '减伤 +8%', '减伤 +12%'],
  dodge: ['闪避 +5%', '闪避 +8%', '闪避 +12%'],
  crit: ['暴击率 +5%', '暴击率 +8%、暴伤 162%', '暴击率 +12%、暴伤 178%'],
  growth: ['经验 +5%', '经验 +10%', '经验 +16%'],
  magnet: ['吸金半径 +1.5', '吸金半径 +2.5', '吸金半径 +4'],
  cast_reach: ['够得着 +6%', '够得着 +12%', '够得着 +20%'],
  cast_area: ['这一下 +8%', '这一下 +14%', '这一下 +22%'],
  star_rain: ['落岩稍勤', '落岩更勤', '落岩更勤'],
  chain_reach: ['覆盖面积小幅提升', '覆盖面积明显提升', '覆盖面积大幅提升'],
}
